/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.da1;

import com.ntdk.dao.loaiSP_DAO;
import com.ntdk.dao.sanPham_DAO;
import com.ntdk.entity.loaiSP;
import com.ntdk.entity.sanPham;
import com.tndk.utils.Auth;
import com.tndk.utils.MsgBox;
import com.tndk.utils.XDate;
import com.tndk.utils.XImage;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class frm_QL_SanPham extends javax.swing.JFrame {

    /**
     * Creates new form frm_QL_SanPham
     */
    public frm_QL_SanPham() {
        initComponents();
        setBtn();
        init_sp();
        init_lsp();
    }

    sanPham_DAO dao_sp = new sanPham_DAO();
    loaiSP_DAO dao_lsp = new loaiSP_DAO();

    int row2 = -1;
    int row1 = -1;

    Color cl_btn = new Color(0, 0, 0, 0);

    public void setBtn() {
        btn_QL_NV.setBackground(cl_btn);
        btnTrangChu.setBackground(cl_btn);
        btn_ThanhToan.setBackground(cl_btn);
        btn_QL_KH.setBackground(cl_btn);
        btn_QL_DT.setBackground(cl_btn);
        btn_doiMatKhau.setBackground(cl_btn);
        btn_dangXuat.setBackground(cl_btn);
    }

    public void DangXuat() {
        Auth.clear();
        new frm_DangNhapJdialog(this, true).setVisible(true);
    }

    public void KetThuc() {
        if (MsgBox.confirm(this, "Bạn muốn kết thúc làm việc")) {
            System.exit(0);
        }
    }

    public void OpenNhanVien() {
        if (Auth.isLogin()) {
            if (!Auth.isManager()) {
                MsgBox.alert(this, "Ban khong co quyen xem nhan vien");
            } else {
                this.dispose();
                new frm_QL_NhanVIen().setVisible(true);
            }
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
    }

    public void OpenThanhToan() {
        if (Auth.isLogin()) {
            this.dispose();
            new frm_QL_ThanhToan().setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
    }

    public void OpenKhachHang() {
        if (Auth.isLogin()) {
            this.dispose();
            new frm_QL_KhachHang().setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
    }

    public void OpenTrangChu() {
        if (Auth.isLogin()) {
            this.dispose();
            new frm_GiaoDienChinh().setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
    }

    public void OpenDoiMatKhau() {

        new frm_DoiMatKhau(this, true).setVisible(true);
    }

    public void OpenDoanhThu() {
        if (Auth.isLogin()) {
            if (!Auth.isManager()) {
                MsgBox.alert(this, "Ban khong co quyen xem doanh thu");
            } else {
                this.dispose();
                new frm_QL_DoanhThu().setVisible(true);
            }
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        cboLoaiSP = new javax.swing.JComboBox<>();
        btnSua = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        txtMaSP = new javax.swing.JTextField();
        txtTenSP = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblHinhSP = new javax.swing.JLabel();
        txtGiaTien = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtSize = new javax.swing.JTextField();
        txtSoLuong = new javax.swing.JTextField();
        txtHang = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtGhiChu = new javax.swing.JTextArea();
        lblMaNV = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBang_SP = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        lblNgayTao = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnXoa = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        btnLamMoi = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        btnSau = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        btnTruoc = new javax.swing.JButton();
        txtTimKiem = new javax.swing.JTextField();
        btnDau = new javax.swing.JButton();
        btnCuoi = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        btnSua1Loai = new javax.swing.JButton();
        btnXoaLoai = new javax.swing.JButton();
        btnThemLoai = new javax.swing.JButton();
        btnLamMoiLoai = new javax.swing.JButton();
        btnSauLoai = new javax.swing.JButton();
        btnTruocLoai = new javax.swing.JButton();
        btnDauLoai = new javax.swing.JButton();
        btnCuoiLoai = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblBangLoai = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        txtMaLoai = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtTenLoai = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnTrangChu = new javax.swing.JButton();
        btn_QL_NV = new javax.swing.JButton();
        btn_ThanhToan = new javax.swing.JButton();
        btn_QL_DT = new javax.swing.JButton();
        btn_QL_KH = new javax.swing.JButton();
        btn_dangXuat = new javax.swing.JButton();
        btn_doiMatKhau = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        cboLoaiSP.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboLoaiSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboLoaiSPActionPerformed(evt);
            }
        });

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        txtMaSP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtMaSPFocusLost(evt);
            }
        });
        txtMaSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaSPActionPerformed(evt);
            }
        });

        txtTenSP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTenSPFocusLost(evt);
            }
        });
        txtTenSP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenSPActionPerformed(evt);
            }
        });

        jLabel3.setText("Mã Sản Phẩm");

        jLabel4.setText("Tên Sản Phẩm");

        lblHinhSP.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        lblHinhSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHinhSPMouseClicked(evt);
            }
        });

        txtGiaTien.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtGiaTienFocusLost(evt);
            }
        });
        txtGiaTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGiaTienActionPerformed(evt);
            }
        });

        jLabel6.setText("Hinh");

        jLabel7.setText("Hãng");

        txtSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSizeActionPerformed(evt);
            }
        });

        txtSoLuong.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSoLuongFocusLost(evt);
            }
        });
        txtSoLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSoLuongActionPerformed(evt);
            }
        });

        txtHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHangActionPerformed(evt);
            }
        });

        jLabel8.setText("Loại Sản Phẩm");

        txtGhiChu.setColumns(20);
        txtGhiChu.setRows(5);
        jScrollPane2.setViewportView(txtGhiChu);

        lblMaNV.setText("Mã nhân viên");

        tblBang_SP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã SP", "Tên SP", "Loại SP", "Số Lượng", "SIze", "Đơn Giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBang_SP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBang_SPMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblBang_SP);

        jLabel9.setText("Ghi Chú");

        lblNgayTao.setText("Ngày Tạo");

        jLabel10.setText("Số Lượng");

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jLabel13.setText("Size");

        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        jLabel14.setText("Giá Tiền");

        btnSau.setText("Sau");
        btnSau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSauActionPerformed(evt);
            }
        });

        jLabel11.setText("Tìm Kiếm");

        btnTruoc.setText("Trước");
        btnTruoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTruocActionPerformed(evt);
            }
        });

        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });

        btnDau.setText("Đầu");
        btnDau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDauActionPerformed(evt);
            }
        });

        btnCuoi.setText("Cuối");
        btnCuoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuoiActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("QUẢN LÝ SẢN PHẨM");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(lblNgayTao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblMaNV, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                            .addComponent(lblHinhSP, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(cboLoaiSP, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtHang)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtTenSP, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                            .addComponent(txtMaSP, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGiaTien)
                                    .addComponent(txtSize)
                                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addComponent(jLabel6))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTruoc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnXoa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnThem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDau, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCuoi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSau, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(299, 299, 299))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtMaSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtTenSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txtHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel8))
                                    .addComponent(lblHinhSP, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtGiaTien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(13, 13, 13)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboLoaiSP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMaNV))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(lblNgayTao))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThem)
                            .addComponent(btnSua))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnXoa)
                            .addComponent(btnLamMoi))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTruoc)
                            .addComponent(btnSau))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDau)
                            .addComponent(btnCuoi))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Sản Phẩm", jPanel2);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setText("QUẢN LÝ LOẠI SẢN PHẨM");

        btnSua1Loai.setText("Sửa");
        btnSua1Loai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSua1LoaiActionPerformed(evt);
            }
        });

        btnXoaLoai.setText("Xóa");
        btnXoaLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaLoaiActionPerformed(evt);
            }
        });

        btnThemLoai.setText("Thêm");
        btnThemLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemLoaiActionPerformed(evt);
            }
        });

        btnLamMoiLoai.setText("Làm mới");
        btnLamMoiLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiLoaiActionPerformed(evt);
            }
        });

        btnSauLoai.setText("Sau");
        btnSauLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSauLoaiActionPerformed(evt);
            }
        });

        btnTruocLoai.setText("Trước");
        btnTruocLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTruocLoaiActionPerformed(evt);
            }
        });

        btnDauLoai.setText("Đầu");
        btnDauLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDauLoaiActionPerformed(evt);
            }
        });

        btnCuoiLoai.setText("Cuối");
        btnCuoiLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuoiLoaiActionPerformed(evt);
            }
        });

        tblBangLoai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Mã Loại", "Tên Loại"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBangLoai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBangLoaiMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblBangLoai);

        jLabel16.setText("Mã loại sản phẩm ");

        txtMaLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaLoaiActionPerformed(evt);
            }
        });

        jLabel17.setText("Tên loại sản phẩm");

        txtTenLoai.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTenLoaiFocusLost(evt);
            }
        });
        txtTenLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenLoaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(278, 278, 278)
                                .addComponent(jLabel15))
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtMaLoai, javax.swing.GroupLayout.DEFAULT_SIZE, 528, Short.MAX_VALUE)
                            .addComponent(txtTenLoai))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTruocLoai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnXoaLoai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnThemLoai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDauLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnSua1Loai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCuoiLoai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSauLoai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnLamMoiLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtMaLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(txtTenLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThemLoai)
                            .addComponent(btnSua1Loai))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnXoaLoai)
                            .addComponent(btnLamMoiLoai))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTruocLoai)
                            .addComponent(btnSauLoai))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnDauLoai)
                            .addComponent(btnCuoiLoai))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        jTabbedPane1.addTab("Loại Sản Phẩm", jPanel4);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 45, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setForeground(new java.awt.Color(0, 102, 102));

        btnTrangChu.setBackground(new java.awt.Color(204, 204, 255));
        btnTrangChu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTrangChu.setForeground(new java.awt.Color(255, 255, 255));
        btnTrangChu.setText("Trang Chủ");
        btnTrangChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrangChuActionPerformed(evt);
            }
        });

        btn_QL_NV.setBackground(new java.awt.Color(204, 204, 255));
        btn_QL_NV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_QL_NV.setForeground(new java.awt.Color(255, 255, 255));
        btn_QL_NV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconNhe/nhanVien.png"))); // NOI18N
        btn_QL_NV.setText("Quản lý nhân viên");
        btn_QL_NV.setBorder(null);
        btn_QL_NV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QL_NVActionPerformed(evt);
            }
        });

        btn_ThanhToan.setBackground(new java.awt.Color(204, 204, 255));
        btn_ThanhToan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_ThanhToan.setForeground(new java.awt.Color(255, 255, 255));
        btn_ThanhToan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconNhe/listClothes.png"))); // NOI18N
        btn_ThanhToan.setText("Thanh Toán");
        btn_ThanhToan.setBorder(null);
        btn_ThanhToan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThanhToanActionPerformed(evt);
            }
        });

        btn_QL_DT.setBackground(new java.awt.Color(204, 204, 255));
        btn_QL_DT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_QL_DT.setForeground(new java.awt.Color(255, 255, 255));
        btn_QL_DT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconNhe/thongke.png"))); // NOI18N
        btn_QL_DT.setText("Doanh thu");
        btn_QL_DT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QL_DTActionPerformed(evt);
            }
        });

        btn_QL_KH.setBackground(new java.awt.Color(204, 204, 255));
        btn_QL_KH.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_QL_KH.setForeground(new java.awt.Color(255, 255, 255));
        btn_QL_KH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/bill.png"))); // NOI18N
        btn_QL_KH.setText("Quản lý khách hàng");
        btn_QL_KH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QL_KHActionPerformed(evt);
            }
        });

        btn_dangXuat.setBackground(new java.awt.Color(204, 204, 255));
        btn_dangXuat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_dangXuat.setForeground(new java.awt.Color(255, 255, 255));
        btn_dangXuat.setText("Đăng xuất");
        btn_dangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangXuatActionPerformed(evt);
            }
        });

        btn_doiMatKhau.setBackground(new java.awt.Color(204, 204, 255));
        btn_doiMatKhau.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_doiMatKhau.setForeground(new java.awt.Color(255, 255, 255));
        btn_doiMatKhau.setText("Đổi mật khẩu");
        btn_doiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_doiMatKhauActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/snapedit_con4.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_QL_NV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnTrangChu, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
            .addComponent(btn_QL_DT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_dangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_doiMatKhau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_ThanhToan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_QL_KH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_QL_NV, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_ThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_QL_KH, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_QL_DT, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_doiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_dangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTrangChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrangChuActionPerformed
        this.OpenTrangChu();
    }//GEN-LAST:event_btnTrangChuActionPerformed

    private void btn_QL_NVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QL_NVActionPerformed
        this.OpenNhanVien();
    }//GEN-LAST:event_btn_QL_NVActionPerformed

    private void btn_ThanhToanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThanhToanActionPerformed
        this.OpenThanhToan();
    }//GEN-LAST:event_btn_ThanhToanActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        this.update_sp();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void txtTenSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenSPActionPerformed

    private void lblHinhSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHinhSPMouseClicked
        if (evt.getClickCount() == 2) {
            this.chonAnh();
        }
    }//GEN-LAST:event_lblHinhSPMouseClicked

    private void txtSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSizeActionPerformed

    private void txtSoLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSoLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSoLuongActionPerformed

    private void txtHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHangActionPerformed

    private void btnSua1LoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSua1LoaiActionPerformed
        this.update_lsp();
    }//GEN-LAST:event_btnSua1LoaiActionPerformed

    private void tblBang_SPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBang_SPMouseClicked
        if (evt.getClickCount() == 2) {
            this.row1 = tblBang_SP.getSelectedRow();
            this.edit_sp();
        }
    }//GEN-LAST:event_tblBang_SPMouseClicked

    private void btnThemLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemLoaiActionPerformed
        this.insert_lsp();
        this.fillComboBoxLoaiSP();
    }//GEN-LAST:event_btnThemLoaiActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        this.delete_sp();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        this.clearForm_sp();
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void btnTruocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTruocActionPerformed
        this.prev_sp();
    }//GEN-LAST:event_btnTruocActionPerformed

    private void btnSauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSauActionPerformed
        this.next_sp();
    }//GEN-LAST:event_btnSauActionPerformed

    private void btnDauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDauActionPerformed
        this.first_sp();
    }//GEN-LAST:event_btnDauActionPerformed

    private void btnCuoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuoiActionPerformed
        this.last_sp();
    }//GEN-LAST:event_btnCuoiActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        this.insert_sp();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnXoaLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaLoaiActionPerformed
        this.delete_lsp();
    }//GEN-LAST:event_btnXoaLoaiActionPerformed

    private void btnLamMoiLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiLoaiActionPerformed
        this.clearForm_lsp();
    }//GEN-LAST:event_btnLamMoiLoaiActionPerformed

    private void btnTruocLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTruocLoaiActionPerformed
        this.prev_lsp();
    }//GEN-LAST:event_btnTruocLoaiActionPerformed

    private void btnSauLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSauLoaiActionPerformed
        this.next_lsp();
    }//GEN-LAST:event_btnSauLoaiActionPerformed

    private void btnDauLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDauLoaiActionPerformed
        this.first_lsp();
    }//GEN-LAST:event_btnDauLoaiActionPerformed

    private void btnCuoiLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuoiLoaiActionPerformed
        this.last_lsp();
    }//GEN-LAST:event_btnCuoiLoaiActionPerformed

    private void tblBangLoaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBangLoaiMouseClicked
        if (evt.getClickCount() == 2) {
            this.row2 = tblBangLoai.getSelectedRow();
            this.edit_lsp();
        }
    }//GEN-LAST:event_tblBangLoaiMouseClicked

    private void txtMaLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaLoaiActionPerformed
        txtMaLoai.setEditable(false);
    }//GEN-LAST:event_txtMaLoaiActionPerformed

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        this.timKiem();
    }//GEN-LAST:event_txtTimKiemActionPerformed

    private void btn_QL_KHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QL_KHActionPerformed
        this.OpenKhachHang();
    }//GEN-LAST:event_btn_QL_KHActionPerformed

    private void btn_doiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_doiMatKhauActionPerformed
        this.OpenDoiMatKhau();
    }//GEN-LAST:event_btn_doiMatKhauActionPerformed

    private void btn_dangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangXuatActionPerformed
        this.DangXuat();
    }//GEN-LAST:event_btn_dangXuatActionPerformed

    private void btn_QL_DTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QL_DTActionPerformed
        this.OpenDoanhThu();
    }//GEN-LAST:event_btn_QL_DTActionPerformed

    private void txtMaSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaSPActionPerformed

    }//GEN-LAST:event_txtMaSPActionPerformed

    private void txtGiaTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGiaTienActionPerformed

    }//GEN-LAST:event_txtGiaTienActionPerformed

    private void txtMaSPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtMaSPFocusLost
        if (!txtMaSP.getText().isEmpty()) {
            String reg = "SP\\d{3,}";
            if (!txtMaSP.getText().trim().matches(reg)) {
                MsgBox.alert(this, "Vui lòng nhập đúng đinh dạng!\nVD: SP001.");
                txtMaSP.setText("");
            }
        }
        if (this.row1 == -1) {
            if (dao_sp.selectById(txtMaSP.getText()) != null) {
                MsgBox.alert(this, "Mã đã tồn tại!");
                txtMaSP.setText("");
            }
        }
    }//GEN-LAST:event_txtMaSPFocusLost

    private void txtGiaTienFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtGiaTienFocusLost
        if (!txtGiaTien.getText().isEmpty()) {
            String reg = "\\d{4,}";
            if (!txtGiaTien.getText().trim().matches(reg)) {
                MsgBox.alert(this, "Vui lòng nhập đúng đinh dạng!\nVD: 10000.");
                txtGiaTien.setText("");
            }
        }
    }//GEN-LAST:event_txtGiaTienFocusLost

    private void txtSoLuongFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSoLuongFocusLost
        if (!txtSoLuong.getText().isEmpty()) {
            String reg = "\\d{1,1000}";
            if (!txtSoLuong.getText().trim().matches(reg)) {
                MsgBox.alert(this, "Vui lòng nhập đúng đinh dạng!\nVD: 10.");
                txtSoLuong.setText("");
            }
        }
    }//GEN-LAST:event_txtSoLuongFocusLost

    private void txtTenSPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTenSPFocusLost
        if (!txtTenSP.getText().isEmpty()) {
            String reg = "[a-zA-Z\\s]+";
            if (!txtTenSP.getText().trim().matches(reg)) {
                MsgBox.alert(this, "Tên không được chứa sô hay ký tự đặc biệt!");
                txtTenSP.setText("");
            }
        }
    }//GEN-LAST:event_txtTenSPFocusLost

    private void txtTenLoaiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTenLoaiFocusLost
        if (!txtTenLoai.getText().isEmpty()) {
            String reg = "[a-zA-Z\\s]+";
            if (!txtTenLoai.getText().trim().matches(reg)) {
                MsgBox.alert(this, "Tên không được chứa sô hay ký tự đặc biệt!");
            }
        }
    }//GEN-LAST:event_txtTenLoaiFocusLost

    private void txtTenLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenLoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenLoaiActionPerformed

    private void cboLoaiSPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboLoaiSPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboLoaiSPActionPerformed

    void updateStatus_lsp() {
        boolean edit = (this.row2 >= 0);
        boolean first = (this.row2 == 0);
        boolean last = (this.row2 == tblBangLoai.getRowCount() - 1);

        btnThemLoai.setEnabled(!edit);
        btnSua1Loai.setEnabled(edit);
        btnXoaLoai.setEnabled(edit);

        btnDauLoai.setEnabled(edit && !first);
        btnTruocLoai.setEnabled(edit && !first);
        btnSauLoai.setEnabled(edit && !last);
        btnCuoiLoai.setEnabled(edit && !last);
    }

    loaiSP getForm_lsp() {
        if (this.batLoiNullLoaiSp()) {
            return null;
        }
        loaiSP lsp = new loaiSP();
        lsp.setTenLoai(txtTenLoai.getText());
        if (this.row2 > 0) {
            lsp.setMaLoai(Integer.parseInt(txtMaLoai.getText()));
        }
        return lsp;
    }

    void setForm_lsp(loaiSP lsp) {
        txtMaLoai.setText(lsp.getMaLoai() + "");
        txtTenLoai.setText(lsp.getTenLoai());
    }

    void fillTable_lsp() {
        DefaultTableModel model = (DefaultTableModel) tblBangLoai.getModel();
        model.setRowCount(0);
        try {
            List<loaiSP> list_lsp = dao_lsp.selectAll();
            for (loaiSP e : list_lsp) {
                Object[] row = {e.getMaLoai(), e.getTenLoai()};
                model.addRow(row);
            }
        } catch (Exception e) {
            e.printStackTrace();
            MsgBox.alert(this, "Lỗi try vấn dữ liệu!");
        }
    }

    void last_lsp() {
        this.row2 = tblBangLoai.getRowCount() - 1;
        this.edit_lsp();
    }

    void next_lsp() {
        if (this.row2 < tblBangLoai.getRowCount() - 1) {
            this.row2++;
            this.edit_lsp();
        }
    }

    void prev_lsp() {
        if (this.row2 > 0) {
            this.row2--;
            this.edit_lsp();
        }
    }

    void first_lsp() {
        this.row2 = 0;
        this.edit_lsp();
    }

    void edit_lsp() {
        int maLoai = (int) tblBangLoai.getValueAt(this.row2, 0);
        loaiSP lsp = dao_lsp.selectById(maLoai);
        this.setForm_lsp(lsp);
        this.updateStatus_lsp();
    }

    void clearForm_lsp() {
        loaiSP lsp = new loaiSP();
        this.setForm_lsp(lsp);
        this.row2 = -1;
        this.updateStatus_lsp();
    }

    void delete_lsp() {
        if (!Auth.isManager()) {
            MsgBox.alert(this, "Bạn không có quyền xóa loại sản phẩm!");
        } else {
            int maLoai = Integer.parseInt(txtMaLoai.getText());
            if (MsgBox.confirm(this, "Bạn thực sự muốn xóa loại sản phẩm này!")) {
                try {
                    dao_lsp.delete(maLoai);
                    this.fillTable_lsp();
                    this.clearForm_lsp();
                    MsgBox.alert(this, "Xóa thành công!");
                } catch (Exception e) {
                    e.printStackTrace();
                    MsgBox.alert(this, "Xóa thất bại!");
                }
            }
        }
    }

    void update_lsp() {
        loaiSP lsp = getForm_lsp();
        try {
            dao_lsp.update(lsp);
            this.fillTable_lsp();
            MsgBox.alert(this, "Cập nhật thành công!");
        } catch (Exception e) {
            e.printStackTrace();
            MsgBox.alert(this, "Cập ngật thất bại!");
        }
    }

    void insert_lsp() {
        loaiSP lsp = getForm_lsp();
        if (lsp == null) {
            return;
        }
        try {
            dao_lsp.insert(lsp);
            this.fillTable_lsp();
            this.clearForm_lsp();
            MsgBox.alert(this, "Thêm mới thành công!");
        } catch (Exception e) {
            e.printStackTrace();
            MsgBox.alert(this, "Thêm mới thất bại!");
        }
    }

    void init_lsp() {
        this.setLocationRelativeTo(null);
        txtMaLoai.setEditable(false);

        this.fillTable_lsp();
        this.row2 = -1;
        this.updateStatus_lsp();
    }
//.....................................................................................................

    void timKiem() {
        this.fillTable_sp();
        this.clearForm_sp();
        this.row1 = -1;
        updateStatus_sp();
    }

    void fillComboBoxLoaiSP() {
        DefaultComboBoxModel model = (DefaultComboBoxModel) cboLoaiSP.getModel();
        model.removeAllElements();
        List<loaiSP> list_lsp = dao_lsp.selectAll();
        for (loaiSP lsp : list_lsp) {
            model.addElement(lsp);
        }
    }

    void chonAnh() {
        // nếu người dùng chọn tệp và nhấn open 
        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            //lấy tệp đc chọn
            File file = fileChooser.getSelectedFile();
            //lưu tệp đc chọn
            XImage.save(file);
            //đọc ảnh từ tệp
            ImageIcon icon = XImage.read(file.getName());
            //lấy đối tượng image từ imageicon
            Image image = icon.getImage();
            //thay đổi kích thước ảnh thành kích thước của lbl
            Image resizeImage = image.getScaledInstance(120, 161, Image.SCALE_DEFAULT);
            //cập nhật ảnh với ảnh đã thay đổi kích thước
            icon.setImage(resizeImage);
            //hiển thị imageicon trên lbl
            lblHinhSP.setIcon(icon);
            //đặt tooltip cho lbl để hiển thị tên của tệp ảnh
            lblHinhSP.setToolTipText(file.getName());
        }
    }

    void updateStatus_sp() {
        boolean edit = (this.row1 >= 0);
        boolean first = (this.row1 == 0);
        boolean last = (this.row1 == tblBang_SP.getRowCount() - 1);

        txtMaSP.setEditable(!edit);
        btnThem.setEnabled(!edit);
        btnSua.setEnabled(edit);
        btnXoa.setEnabled(edit);

        btnDau.setEnabled(edit && !first);
        btnTruoc.setEnabled(edit && !first);
        btnSau.setEnabled(edit && !last);
        btnCuoi.setEnabled(edit && !last);
    }

    sanPham getForm() {
        if (this.batLoiKoNullSp()) {
            return null;
        }
        sanPham sp = new sanPham();
        sp.setMaSP(txtMaSP.getText());
        sp.setTenSP(txtTenSP.getText());
        int maLoai = ((loaiSP) cboLoaiSP.getSelectedItem()).getMaLoai();
        sp.setLoaiSP(maLoai);
        sp.setHangSP(txtHang.getText());
        sp.setSoLuong(Integer.parseInt(txtSoLuong.getText()));
        sp.setGiaTien(Float.parseFloat(txtGiaTien.getText()));
        sp.setSize(txtSize.getText());
        sp.setGhiChu(txtGhiChu.getText());
        sp.setMaNV(Auth.user.getMaNV());
        sp.setHinh(lblHinhSP.getToolTipText());
        sp.setNgayTao(new Date());

        return sp;
    }

    public boolean batLoiKoNullSp() {
        if (txtMaSP.getText().isEmpty() || txtTenSP.getText().isEmpty() || txtHang.getText().isEmpty() || txtSoLuong.getText().isEmpty() || txtGiaTien.getText().isEmpty()
                || txtSize.getText().isEmpty()) {
            MsgBox.alert(this, "Không được bỏ trống");
            return true;
        } else {
            return false;
        }

    }

    public boolean batLoiNullLoaiSp() {
        if (txtTenLoai.getText().isEmpty()) {
            MsgBox.alert(this, "Không được bỏ trống");
            return true;
        } else {
            return false;
        }
    }

    void setForm(sanPham sp) {
        if (row1 < 0) {
            cboLoaiSP.setSelectedIndex(sp.getLoaiSP());
        } else {
            cboLoaiSP.setSelectedIndex(sp.getLoaiSP() - 1);
        }

        txtMaSP.setText(sp.getMaSP());
        txtTenSP.setText(sp.getTenSP());
        txtHang.setText(sp.getHangSP());
        txtSoLuong.setText(sp.getSoLuong() + "");
        txtGiaTien.setText(sp.getGiaTien() + "");
        txtSize.setText(sp.getSize());
        txtGhiChu.setText(sp.getGhiChu());
        lblMaNV.setText(Auth.user.getMaNV());

        if (sp.getNgayTao() == null) {
            SimpleDateFormat formater = new SimpleDateFormat("yyyy-MM-dd");
            String text = formater.format(new Date());
            lblNgayTao.setText(text);
        } else {
            lblNgayTao.setText(XDate.toString(sp.getNgayTao(), "yyyy-MM-dd"));
        }

        if (sp.getHinh() != null) {
            ImageIcon icon = XImage.read(sp.getHinh());
            Image image = icon.getImage();
            Image resizeImage = image.getScaledInstance(120, 161, Image.SCALE_DEFAULT);
            icon.setImage(resizeImage);
            lblHinhSP.setIcon(icon);
            lblHinhSP.setToolTipText(sp.getHinh());
        }
    }

    public String getTenLoaiSp(int ma) {
        List<loaiSP> tenlsp = dao_lsp.selectAll();
        for (loaiSP lspNeP : tenlsp) {
            if (lspNeP.getMaLoai() == ma) {
                return lspNeP.getTenLoai();
            }
        }
        return "";
    }

    void fillTable_sp() {
        DefaultTableModel model = (DefaultTableModel) tblBang_SP.getModel();
        model.setRowCount(0);
        try {
            String timTen = txtTimKiem.getText();
            List<sanPham> list_sp = dao_sp.selectByKeyWord(timTen);
            for (sanPham e : list_sp) {
                String ten = getTenLoaiSp(e.getLoaiSP());
                Object[] row = {e.getMaSP(), e.getTenSP(), ten, e.getSoLuong(), e.getSize(), e.getGiaTien()};
                model.addRow(row);
            }
        } catch (Exception e) {
            e.printStackTrace();
            MsgBox.alert(this, "Lỗi try vấn dữ liệu!");
        }
    }

    void last_sp() {
        this.row1 = tblBang_SP.getRowCount() - 1;
        this.edit_sp();
    }

    void next_sp() {
        if (this.row1 < tblBang_SP.getRowCount() - 1) {
            this.row1++;
            this.edit_sp();
        }
    }

    void prev_sp() {
        if (this.row1 > 0) {
            this.row1--;
            this.edit_sp();
        }
    }

    void first_sp() {
        this.row1 = 0;
        this.edit_sp();
    }

    void edit_sp() {
        String maSP = (String) tblBang_SP.getValueAt(this.row1, 0);
        sanPham sp = dao_sp.selectById(maSP);
        this.setForm(sp);
        this.updateStatus_sp();
    }

    void clearForm_sp() {
        sanPham sp = new sanPham();
        this.row1 = -1;
        this.setForm(sp);
        this.updateStatus_sp();
    }

    void delete_sp() {
        if (!Auth.isManager()) {
            MsgBox.alert(this, "Bạn không có quyền xóa sản phẩm!");
        } else {
            String maSP = txtMaSP.getText();
            if (MsgBox.confirm(this, "Bạn thực sự muốn xóa sản phẩm này!")) {
                try {
                    dao_sp.delete(maSP);
                    this.fillTable_sp();
                    this.clearForm_sp();
                    MsgBox.alert(this, "Xóa thành công!");
                } catch (Exception e) {
                    e.printStackTrace();
                    MsgBox.alert(this, "Xóa thất bại!");
                }
            }
        }
    }

    void update_sp() {
        sanPham sp = getForm();
        try {
            dao_sp.update(sp);
            this.fillTable_sp();
            MsgBox.alert(this, "Cập nhật thành công!");
        } catch (Exception e) {
            e.printStackTrace();
            MsgBox.alert(this, "Cập ngật thất bại!");
        }
    }

    void insert_sp() {
        sanPham sp = getForm();
        if (sp == null) {
            return;
        }
        try {
            dao_sp.insert(sp);
            this.fillTable_sp();
            this.clearForm_sp();
            MsgBox.alert(this, "Thêm mới thành công!");
        } catch (Exception e) {
            e.printStackTrace();
            MsgBox.alert(this, "Thêm mới thất bại!");
        }
    }

    void init_sp() {
        this.setLocationRelativeTo(null);
        this.fillComboBoxLoaiSP();

        this.fillTable_sp();
        this.row1 = -1;
        this.updateStatus_sp();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_QL_SanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_QL_SanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_QL_SanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_QL_SanPham.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_QL_SanPham().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCuoi;
    private javax.swing.JButton btnCuoiLoai;
    private javax.swing.JButton btnDau;
    private javax.swing.JButton btnDauLoai;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnLamMoiLoai;
    private javax.swing.JButton btnSau;
    private javax.swing.JButton btnSauLoai;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnSua1Loai;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThemLoai;
    private javax.swing.JButton btnTrangChu;
    private javax.swing.JButton btnTruoc;
    private javax.swing.JButton btnTruocLoai;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoaLoai;
    private javax.swing.JButton btn_QL_DT;
    private javax.swing.JButton btn_QL_KH;
    private javax.swing.JButton btn_QL_NV;
    private javax.swing.JButton btn_ThanhToan;
    private javax.swing.JButton btn_dangXuat;
    private javax.swing.JButton btn_doiMatKhau;
    private javax.swing.JComboBox<String> cboLoaiSP;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblHinhSP;
    private javax.swing.JLabel lblMaNV;
    private javax.swing.JLabel lblNgayTao;
    private javax.swing.JTable tblBangLoai;
    private javax.swing.JTable tblBang_SP;
    private javax.swing.JTextArea txtGhiChu;
    private javax.swing.JTextField txtGiaTien;
    private javax.swing.JTextField txtHang;
    private javax.swing.JTextField txtMaLoai;
    private javax.swing.JTextField txtMaSP;
    private javax.swing.JTextField txtSize;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenLoai;
    private javax.swing.JTextField txtTenSP;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
