/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.da1;

import com.ntdk.entity.nhanVien;
import com.tndk.utils.Auth;
import com.tndk.utils.MsgBox;
import com.tndk.utils.XImage;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.Timer;

/**
 *
 * @author Asus
 */
public class frm_GiaoDienChinh extends javax.swing.JFrame {

    /**
     * Creates new form frm_GiaoDienChinh
     */
    public frm_GiaoDienChinh() {
        initComponents();
        init();
    }
    
    
     public void init() {
        setLocationRelativeTo(null);
        new Timer(1000, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                Date now = new Date();
                SimpleDateFormat format = new SimpleDateFormat("hh:mm:ss a");
                lbl_DongHo.setText(format.format(now));
            }
        }).start();

        new frm_ManHinhChao(this, true).setVisible(true);
        new frm_DangNhap(this, true).setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btn_DangXuat = new javax.swing.JButton();
        btn_KetThuc = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JToolBar.Separator();
        btn_SanPham = new javax.swing.JButton();
        btn_NhanVien = new javax.swing.JButton();
        btn_HoaDon = new javax.swing.JButton();
        jSeparator8 = new javax.swing.JToolBar.Separator();
        btnHuongDan = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lbl_TrangThai = new javax.swing.JLabel();
        lbl_DongHo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        Minu_HeThong = new javax.swing.JMenu();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        Mini_DoiMk = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        Mini_DangXuat = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        Mini_KetThuc = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItem4 = new javax.swing.JMenuItem();
        Minu_ThongKe = new javax.swing.JMenu();
        Mini_DoanhThu = new javax.swing.JMenuItem();
        Minu_TroGiup = new javax.swing.JMenu();
        Mini_HuongDan = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        Mini_GioiThieu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        btn_DangXuat.setText("Đăng xuất");
        btn_DangXuat.setFocusable(false);
        btn_DangXuat.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_DangXuat.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_DangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DangXuatActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_DangXuat);

        btn_KetThuc.setText("Kết thúc");
        btn_KetThuc.setFocusable(false);
        btn_KetThuc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_KetThuc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_KetThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_KetThucActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_KetThuc);
        jToolBar1.add(jSeparator7);

        btn_SanPham.setText("Sản Phẩm");
        btn_SanPham.setFocusable(false);
        btn_SanPham.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_SanPham.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_SanPham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SanPhamActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_SanPham);

        btn_NhanVien.setText("Nhân Viên");
        btn_NhanVien.setFocusable(false);
        btn_NhanVien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_NhanVien.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_NhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_NhanVienActionPerformed(evt);
            }
        });
        jToolBar1.add(btn_NhanVien);

        btn_HoaDon.setText("Hóa Đơn");
        btn_HoaDon.setFocusable(false);
        btn_HoaDon.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_HoaDon.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btn_HoaDon);
        jToolBar1.add(jSeparator8);

        btnHuongDan.setText("Hướng dẫn");
        btnHuongDan.setFocusable(false);
        btnHuongDan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHuongDan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(btnHuongDan);

        lbl_TrangThai.setText("SHop Thời Trang @NTDK");

        lbl_DongHo.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lbl_DongHoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_TrangThai)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbl_DongHo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_TrangThai)
                    .addComponent(lbl_DongHo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        Minu_HeThong.setText("Hệ Thống");
        Minu_HeThong.add(jSeparator6);

        Mini_DoiMk.setText("Đổi Mật Khẩu");
        Mini_DoiMk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mini_DoiMkActionPerformed(evt);
            }
        });
        Minu_HeThong.add(Mini_DoiMk);
        Minu_HeThong.add(jSeparator1);

        Mini_DangXuat.setText("Đăng Xuất");
        Mini_DangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mini_DangXuatActionPerformed(evt);
            }
        });
        Minu_HeThong.add(Mini_DangXuat);
        Minu_HeThong.add(jSeparator2);

        Mini_KetThuc.setText("Kết Thúc");
        Mini_KetThuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mini_KetThucActionPerformed(evt);
            }
        });
        Minu_HeThong.add(Mini_KetThuc);

        jMenuBar1.add(Minu_HeThong);

        jMenu1.setText("Quản lý");

        jMenuItem1.setText("Sản Phẩm");
        jMenu1.add(jMenuItem1);
        jMenu1.add(jSeparator3);

        jMenuItem2.setText("Nhân Viên");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator4);

        jMenuItem3.setText("Khách hàng");
        jMenu1.add(jMenuItem3);
        jMenu1.add(jSeparator5);

        jMenuItem4.setText("Hóa Đơn");
        jMenu1.add(jMenuItem4);

        jMenuBar1.add(jMenu1);

        Minu_ThongKe.setText("Thống kê");

        Mini_DoanhThu.setText("Doanh thu");
        Mini_DoanhThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mini_DoanhThuActionPerformed(evt);
            }
        });
        Minu_ThongKe.add(Mini_DoanhThu);

        jMenuBar1.add(Minu_ThongKe);

        Minu_TroGiup.setText("Trợ Giúp");

        Mini_HuongDan.setText("Hướng dẫn sử dụng");
        Mini_HuongDan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mini_HuongDanActionPerformed(evt);
            }
        });
        Minu_TroGiup.add(Mini_HuongDan);
        Minu_TroGiup.add(jSeparator10);

        Mini_GioiThieu.setText("Giới thiệu sản phẩm");
        Mini_GioiThieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Mini_GioiThieuActionPerformed(evt);
            }
        });
        Minu_TroGiup.add(Mini_GioiThieu);

        jMenuBar1.add(Minu_TroGiup);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 649, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 378, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Mini_DoiMkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mini_DoiMkActionPerformed
       
    }//GEN-LAST:event_Mini_DoiMkActionPerformed

    private void Mini_DangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mini_DangXuatActionPerformed
        DangXuat();
    }//GEN-LAST:event_Mini_DangXuatActionPerformed

    private void Mini_KetThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mini_KetThucActionPerformed
        KetThuc();
    }//GEN-LAST:event_Mini_KetThucActionPerformed

    private void Mini_DoanhThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mini_DoanhThuActionPerformed
        
    }//GEN-LAST:event_Mini_DoanhThuActionPerformed

    private void Mini_HuongDanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mini_HuongDanActionPerformed
        
    }//GEN-LAST:event_Mini_HuongDanActionPerformed

    private void Mini_GioiThieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Mini_GioiThieuActionPerformed
        
    }//GEN-LAST:event_Mini_GioiThieuActionPerformed

    private void lbl_DongHoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lbl_DongHoAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_DongHoAncestorAdded

    private void btn_KetThucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_KetThucActionPerformed
        KetThuc();
    }//GEN-LAST:event_btn_KetThucActionPerformed

    private void btn_NhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_NhanVienActionPerformed
        OpenNhanVien();
    }//GEN-LAST:event_btn_NhanVienActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        OpenNhanVien();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void btn_SanPhamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SanPhamActionPerformed
       OpenSanPham();
    }//GEN-LAST:event_btn_SanPhamActionPerformed

    private void btn_DangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DangXuatActionPerformed
        DangXuat();
    }//GEN-LAST:event_btn_DangXuatActionPerformed

    
    public void DangXuat() {
        Auth.clear();
        new frm_DangNhap(this, true).setVisible(true);
    }

    public void KetThuc() {
        if (MsgBox.confirm(this, "Bạn muốn kết thúc làm việc")) {
            System.exit(0);
        }
    }
    
    public void OpenNhanVien(){
        if (Auth.isLogin()) {
            new frm_QLNhanVien(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
    }
    
    public void OpenSanPham(){
        if (Auth.isLogin()) {
            new frm_QlSanPham(this, true).setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_GiaoDienChinh.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_GiaoDienChinh().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Mini_DangXuat;
    private javax.swing.JMenuItem Mini_DoanhThu;
    private javax.swing.JMenuItem Mini_DoiMk;
    private javax.swing.JMenuItem Mini_GioiThieu;
    private javax.swing.JMenuItem Mini_HuongDan;
    private javax.swing.JMenuItem Mini_KetThuc;
    private javax.swing.JMenu Minu_HeThong;
    private javax.swing.JMenu Minu_ThongKe;
    private javax.swing.JMenu Minu_TroGiup;
    private javax.swing.JButton btnHuongDan;
    private javax.swing.JButton btn_DangXuat;
    private javax.swing.JButton btn_HoaDon;
    private javax.swing.JButton btn_KetThuc;
    private javax.swing.JButton btn_NhanVien;
    private javax.swing.JButton btn_SanPham;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JToolBar.Separator jSeparator7;
    private javax.swing.JToolBar.Separator jSeparator8;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lbl_DongHo;
    private javax.swing.JLabel lbl_TrangThai;
    // End of variables declaration//GEN-END:variables
}
