/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.da1;

import com.ntdk.dao.loaiSP_DAO;
import com.ntdk.entity.loaiSP;
import com.tndk.utils.MsgBox;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class frm_quanLyLoaiSP extends javax.swing.JFrame {

    /**
     * Creates new form frm_quanLyLoaiSP
     */
    loaiSP_DAO dao = new loaiSP_DAO();
    int row = -1;
    public frm_quanLyLoaiSP() {
        initComponents();
    }
    
   
    private void them() {
        String maLoai = txt_maLoai.getText();
        String tenLoai = txt_tenLoai.getText();
        
        loaiSP sp = new loaiSP(maLoai, tenLoai);

    }

    private void sua() {
        int selectedRow = tbl_bangLoaiSP.getSelectedRow();
        
        if (selectedRow == -1) {
            MsgBox.alert(this, "Vui lòng chọn dòng cần sửa!");
            return;
        }
        
        String maLoai = txt_maLoai.getText();
        String tenLoai = txt_tenLoai.getText();
        
        loaiSP sp = new loaiSP(maLoai, tenLoai);

    }

    private void xoa() {
        int selectedRow = tbl_bangLoaiSP.getSelectedRow();
        
        if (selectedRow == -1) {
            MsgBox.alert(this, "Vui lòng chọn dòng cần xóa!");
            return;
        }
        
        String maLoai = (String) tbl_bangLoaiSP.getValueAt(selectedRow, 0);

    }

    private void clearForm() {
        txt_maLoai.setText("");
        txt_tenLoai.setText("");
        txt_maLoai.requestFocus();
    }

    private void edit() {
        int selectedRow = tbl_bangLoaiSP.getSelectedRow();
        
        if (selectedRow == -1) {
            return;
        }
        
        String maLoai = (String) tbl_bangLoaiSP.getValueAt(selectedRow, 0);
        String tenLoai = (String) tbl_bangLoaiSP.getValueAt(selectedRow, 1);
        
        txt_maLoai.setText(maLoai);
        txt_tenLoai.setText(tenLoai);
    }

    private void lui() {
        int row = tbl_bangLoaiSP.getSelectedRow();
        
        if (row > 0) {
            tbl_bangLoaiSP.setRowSelectionInterval(row - 1, row - 1);
            tbl_bangLoaiSPMouseClicked(null); 
        }
    }

    private void tien() {
        int row = tbl_bangLoaiSP.getSelectedRow();
        int rowCount = tbl_bangLoaiSP.getRowCount();
        
        if (row < rowCount - 1) {
            tbl_bangLoaiSP.setRowSelectionInterval(row + 1, row + 1);
            tbl_bangLoaiSPMouseClicked(null); 
        }
    }

    private void Cuoi() {
        int rowCount = tbl_bangLoaiSP.getRowCount();
        
        if (rowCount > 0) {
            tbl_bangLoaiSP.setRowSelectionInterval(rowCount - 1, rowCount - 1);
            tbl_bangLoaiSPMouseClicked(null); 
        }
    }
    public void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tbl_bangLoaiSP.getModel();
        model.setRowCount(0);
        try {
            String keyword = txt_timKiem.getText();
            List<loaiSP> list = dao.selectAll();
            for (loaiSP lsp : list) {
                Object[] row = {lsp.getMaLoai(),lsp.getTenLoai()};
                model.addRow(row);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "lỗi truy vấn dữ liệu");
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabs = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_bangLoaiSP = new javax.swing.JTable();
        GhiChu = new javax.swing.JPanel();
        txt_maLoai = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_tenLoai = new javax.swing.JTextField();
        txt_timKiem = new javax.swing.JTextField();
        btn_Lui = new javax.swing.JButton();
        btn_Tien = new javax.swing.JButton();
        btn_CuoiDs = new javax.swing.JButton();
        btn_Them = new javax.swing.JButton();
        btn_Sua = new javax.swing.JButton();
        btn_Xoa = new javax.swing.JButton();
        btn_LamMoi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_DauTrang = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl_bangLoaiSP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "MaCd", "TenCd", "Hoc Phi", "ThoiLuong"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_bangLoaiSP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_bangLoaiSPMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbl_bangLoaiSPMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_bangLoaiSP);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 547, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tabs.addTab("Danh sách", jPanel2);

        txt_maLoai.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_maLoaiFocusLost(evt);
            }
        });
        txt_maLoai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_maLoaiMouseClicked(evt);
            }
        });
        txt_maLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_maLoaiActionPerformed(evt);
            }
        });

        jLabel2.setText("Mã loại:");

        jLabel3.setText("Tên loại:");

        jLabel4.setText("Tìm kiếm:");

        txt_tenLoai.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_tenLoaiFocusLost(evt);
            }
        });
        txt_tenLoai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_tenLoaiActionPerformed(evt);
            }
        });

        txt_timKiem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_timKiemFocusLost(evt);
            }
        });
        txt_timKiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_timKiemMouseClicked(evt);
            }
        });
        txt_timKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_timKiemKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_timKiemKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout GhiChuLayout = new javax.swing.GroupLayout(GhiChu);
        GhiChu.setLayout(GhiChuLayout);
        GhiChuLayout.setHorizontalGroup(
            GhiChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GhiChuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(GhiChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(GhiChuLayout.createSequentialGroup()
                        .addGroup(GhiChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(GhiChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_maLoai, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                            .addComponent(txt_tenLoai)
                            .addComponent(txt_timKiem))))
                .addGap(0, 42, Short.MAX_VALUE))
        );
        GhiChuLayout.setVerticalGroup(
            GhiChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GhiChuLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(GhiChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_maLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(GhiChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GhiChuLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(GhiChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_timKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(GhiChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_tenLoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        tabs.addTab("Cập nhật", GhiChu);

        btn_Lui.setText("<<");
        btn_Lui.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LuiActionPerformed(evt);
            }
        });

        btn_Tien.setText(">>");
        btn_Tien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TienActionPerformed(evt);
            }
        });

        btn_CuoiDs.setText(">|");
        btn_CuoiDs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CuoiDsActionPerformed(evt);
            }
        });

        btn_Them.setText("Thêm");
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });

        btn_Sua.setText("Sửa");
        btn_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaActionPerformed(evt);
            }
        });

        btn_Xoa.setText("Xóa");
        btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });

        btn_LamMoi.setText("Làm mới");
        btn_LamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LamMoiActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("QUẢN LÍ LOẠI SẢN PHẨM");

        btn_DauTrang.setText("|<");
        btn_DauTrang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DauTrangActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btn_Them)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_LamMoi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_DauTrang, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Lui, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_Tien, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_CuoiDs, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabs, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Them)
                    .addComponent(btn_Sua)
                    .addComponent(btn_Xoa)
                    .addComponent(btn_LamMoi)
                    .addComponent(btn_DauTrang)
                    .addComponent(btn_Lui)
                    .addComponent(btn_Tien)
                    .addComponent(btn_CuoiDs))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_bangLoaiSPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_bangLoaiSPMouseClicked
        if (evt.getClickCount() == 2) {
            this.row = tbl_bangLoaiSP.getSelectedRow();
            this.edit();
        }
    }//GEN-LAST:event_tbl_bangLoaiSPMouseClicked

    private void tbl_bangLoaiSPMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_bangLoaiSPMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_bangLoaiSPMousePressed

    private void txt_maLoaiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_maLoaiFocusLost
        String maSP = txt_maLoai.getText();
    }//GEN-LAST:event_txt_maLoaiFocusLost

    private void txt_maLoaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_maLoaiMouseClicked

    }//GEN-LAST:event_txt_maLoaiMouseClicked

    private void txt_maLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_maLoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_maLoaiActionPerformed

    private void txt_tenLoaiFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_tenLoaiFocusLost
        String tenSP = txt_tenLoai.getText();
    }//GEN-LAST:event_txt_tenLoaiFocusLost

    private void txt_tenLoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_tenLoaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tenLoaiActionPerformed

    private void txt_timKiemFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_timKiemFocusLost
        String loaiSP = txt_timKiem.getText();
    }//GEN-LAST:event_txt_timKiemFocusLost

    private void txt_timKiemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_timKiemMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_timKiemMouseClicked

    private void txt_timKiemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_timKiemKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_timKiemKeyPressed

    private void txt_timKiemKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_timKiemKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_timKiemKeyReleased

    private void btn_LuiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LuiActionPerformed
        lui();
    }//GEN-LAST:event_btn_LuiActionPerformed

    private void btn_TienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TienActionPerformed
        tien();
    }//GEN-LAST:event_btn_TienActionPerformed

    private void btn_CuoiDsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CuoiDsActionPerformed
        Cuoi();
    }//GEN-LAST:event_btn_CuoiDsActionPerformed

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
        them();
    }//GEN-LAST:event_btn_ThemActionPerformed

    private void btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaActionPerformed
        sua();
    }//GEN-LAST:event_btn_SuaActionPerformed

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed
        xoa();
    }//GEN-LAST:event_btn_XoaActionPerformed

    private void btn_LamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LamMoiActionPerformed
        clearForm();
    }//GEN-LAST:event_btn_LamMoiActionPerformed

    private void btn_DauTrangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DauTrangActionPerformed
        
    }//GEN-LAST:event_btn_DauTrangActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_quanLyLoaiSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_quanLyLoaiSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_quanLyLoaiSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_quanLyLoaiSP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_quanLyLoaiSP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GhiChu;
    private javax.swing.JButton btn_CuoiDs;
    private javax.swing.JButton btn_DauTrang;
    private javax.swing.JButton btn_LamMoi;
    private javax.swing.JButton btn_Lui;
    private javax.swing.JButton btn_Sua;
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_Tien;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JTable tbl_bangLoaiSP;
    private javax.swing.JTextField txt_maLoai;
    private javax.swing.JTextField txt_tenLoai;
    private javax.swing.JTextField txt_timKiem;
    // End of variables declaration//GEN-END:variables
}
