/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.da1;

import com.ntdk.dao.hoaDonChiTiet_DAO;
import com.ntdk.dao.hoaDon_DAO;
import com.ntdk.dao.khachHang_DAO;
import com.ntdk.dao.sanPham_DAO;
import com.ntdk.entity.KhachHang;
import com.ntdk.entity.hoaDon;
import com.ntdk.entity.hoaDonChiTiet;
import com.ntdk.entity.loaiSP;
import com.ntdk.entity.nhanVien;
import com.ntdk.entity.sanPham;
import com.tndk.utils.Auth;
import com.tndk.utils.MsgBox;
import com.tndk.utils.XDate;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.print.PrinterException;
import java.sql.Time;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Timer;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dangt
 */
public class frm_QL_ThanhToan extends javax.swing.JFrame {

    /**
     * Creates new form frm_QL_NhanVIen
     */
    sanPham_DAO dao = new sanPham_DAO();
    khachHang_DAO khDao = new khachHang_DAO();
    hoaDon_DAO dao_hd = new hoaDon_DAO();
    hoaDonChiTiet_DAO dao_hdct = new hoaDonChiTiet_DAO();
    Color cl_btn = new Color(0, 0, 0, 0);

    public frm_QL_ThanhToan() {
        initComponents();
        setBtn();
        this.fillTableSanPham();
    }

    int row = -1;

    public void setBtn() {
        btn_QL_NV.setBackground(cl_btn);
        btn_QL_SP.setBackground(cl_btn);
        btn_TrangChu.setBackground(cl_btn);
        btn_QL_KH.setBackground(cl_btn);
        btn_QL_DT.setBackground(cl_btn);
        btn_doiMatKhau.setBackground(cl_btn);
        btn_dangXuat.setBackground(cl_btn);

    }

    public void DangXuat() {
        Auth.clear();
        new frm_DangNhapJdialog(this, true).setVisible(true);
    }

    public void KetThuc() {
        if (MsgBox.confirm(this, "Bạn muốn kết thúc làm việc")) {
            System.exit(0);
        }
    }

    public void OpenNhanVien() {
        if (Auth.isLogin()) {
            if (!Auth.isManager()) {
                MsgBox.alert(this, "Ban khong co quyen xem nhan vien");

            } else {
                this.dispose();
                new frm_QL_NhanVIen().setVisible(true);
            }
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
    }

    public void OpenTrangChu() {
        if (Auth.isLogin()) {
            this.dispose();
            new frm_GiaoDienChinh().setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
    }

    public void OpenKhachHang() {
        if (Auth.isLogin()) {
            this.dispose();
            new frm_QL_KhachHang().setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
    }

    public void OpenSanPham() {
        if (Auth.isLogin()) {
            this.dispose();
            new frm_QL_SanPham().setVisible(true);
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
    }

    public void OpenDoiMatKhau() {

        new frm_DoiMatKhau(this, true).setVisible(true);
    }

    public void OpenDoanhThu() {
        if (Auth.isLogin()) {
            if (!Auth.isManager()) {
                MsgBox.alert(this, "Ban khong co quyen xem doanh thu");

            } else {
                this.dispose();
                new frm_QL_DoanhThu().setVisible(true);
            }
        } else {
            MsgBox.alert(this, "Vui lòng đăng nhập");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        btn_QL_SP = new javax.swing.JButton();
        btn_QL_NV = new javax.swing.JButton();
        btn_TrangChu = new javax.swing.JButton();
        btn_QL_DT = new javax.swing.JButton();
        btn_QL_KH = new javax.swing.JButton();
        btn_dangXuat = new javax.swing.JButton();
        btn_doiMatKhau = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_sanPhamCho = new javax.swing.JTable();
        btnSua = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnLamMoi = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblBang_S = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        txtTimKiem = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnThemKH = new javax.swing.JButton();
        txtSDT = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JTextField();
        txt_TienThu = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblGiamGia = new javax.swing.JLabel();
        btnResetAll = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        b = new javax.swing.JTextArea();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbl_tienKhachDua = new javax.swing.JLabel();
        btnTinhTien = new javax.swing.JButton();
        btnXuatHoaDon = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lbl_TongTien = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_TienThua = new javax.swing.JLabel();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setForeground(new java.awt.Color(0, 102, 102));

        btn_QL_SP.setBackground(new java.awt.Color(204, 204, 255));
        btn_QL_SP.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_QL_SP.setForeground(new java.awt.Color(255, 255, 255));
        btn_QL_SP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconNhe/sanPham.png"))); // NOI18N
        btn_QL_SP.setText("Quản lý sản phẩm");
        btn_QL_SP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QL_SPActionPerformed(evt);
            }
        });

        btn_QL_NV.setBackground(new java.awt.Color(204, 204, 255));
        btn_QL_NV.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_QL_NV.setForeground(new java.awt.Color(255, 255, 255));
        btn_QL_NV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconNhe/nhanVien.png"))); // NOI18N
        btn_QL_NV.setText("Quản lý nhân viên");
        btn_QL_NV.setBorder(null);
        btn_QL_NV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QL_NVActionPerformed(evt);
            }
        });

        btn_TrangChu.setBackground(new java.awt.Color(204, 204, 255));
        btn_TrangChu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_TrangChu.setForeground(new java.awt.Color(255, 255, 255));
        btn_TrangChu.setText("Trang Chủ");
        btn_TrangChu.setBorder(null);
        btn_TrangChu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TrangChuActionPerformed(evt);
            }
        });

        btn_QL_DT.setBackground(new java.awt.Color(204, 204, 255));
        btn_QL_DT.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_QL_DT.setForeground(new java.awt.Color(255, 255, 255));
        btn_QL_DT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IconNhe/thongke.png"))); // NOI18N
        btn_QL_DT.setText("Doanh thu");
        btn_QL_DT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QL_DTActionPerformed(evt);
            }
        });

        btn_QL_KH.setBackground(new java.awt.Color(204, 204, 255));
        btn_QL_KH.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_QL_KH.setForeground(new java.awt.Color(255, 255, 255));
        btn_QL_KH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/bill.png"))); // NOI18N
        btn_QL_KH.setText("Quản lý khách hàng");
        btn_QL_KH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QL_KHActionPerformed(evt);
            }
        });

        btn_dangXuat.setBackground(new java.awt.Color(204, 204, 255));
        btn_dangXuat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_dangXuat.setForeground(new java.awt.Color(255, 255, 255));
        btn_dangXuat.setText("Đăng xuất");
        btn_dangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangXuatActionPerformed(evt);
            }
        });

        btn_doiMatKhau.setBackground(new java.awt.Color(204, 204, 255));
        btn_doiMatKhau.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_doiMatKhau.setForeground(new java.awt.Color(255, 255, 255));
        btn_doiMatKhau.setText("Đổi mật khẩu");
        btn_doiMatKhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_doiMatKhauActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/anh/snapedit_con4.png"))); // NOI18N

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder("Sản Phẩm Chờ"));

        tbl_sanPhamCho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã SP", "Tên SP", "Số lượng", "Size", "Giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_sanPhamCho.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tbl_sanPhamChoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
                tbl_sanPhamChoAncestorMoved(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane4.setViewportView(tbl_sanPhamCho);

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnLamMoi.setText("Làm mới");
        btnLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnThem)
                .addGap(18, 18, 18)
                .addComponent(btnSua)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXoa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(btnLamMoi)
                .addGap(16, 16, 16))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnSua)
                    .addComponent(btnXoa)
                    .addComponent(btnLamMoi))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh Sách Sản Phẩm"));
        jPanel3.setPreferredSize(new java.awt.Dimension(283, 189));

        tblBang_S.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã SP", "Tên SP", "Loại SP", "Số lượng", "Size", "Đơn giá"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBang_S.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tblBang_SAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tblBang_S.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBang_SMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblBang_S);

        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTimKiem)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông Tin Khách Hàng"));

        btnThemKH.setText("Thêm");
        btnThemKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemKHActionPerformed(evt);
            }
        });

        txtSDT.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtSDTAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        txtSDT.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSDTFocusLost(evt);
            }
        });
        txtSDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSDTActionPerformed(evt);
            }
        });

        txtHoTen.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtHoTenFocusLost(evt);
            }
        });

        txt_TienThu.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_TienThuFocusLost(evt);
            }
        });
        txt_TienThu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TienThuActionPerformed(evt);
            }
        });

        jLabel2.setText("Tiền Thu");

        lblGiamGia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblGiamGia.setForeground(new java.awt.Color(0, 255, 51));
        lblGiamGia.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnResetAll.setText("Lam moi");
        btnResetAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetAllActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txt_TienThu, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnResetAll))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnThemKH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblGiamGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGiamGia, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_TienThu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnResetAll))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThemKH)
                .addGap(111, 111, 111))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder("Hóa Đơn"));

        b.setColumns(20);
        b.setRows(5);
        jScrollPane5.setViewportView(b);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jScrollPane5)
                .addContainerGap())
        );

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Cập Nhật Thông Tin Hóa Đơn"));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Tổng Tiền:");

        lbl_tienKhachDua.setBackground(new java.awt.Color(255, 0, 0));
        lbl_tienKhachDua.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_tienKhachDua.setForeground(new java.awt.Color(255, 0, 0));
        lbl_tienKhachDua.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_tienKhachDua.setText("0 VNĐ");

        btnTinhTien.setText("Tính Tiền");
        btnTinhTien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTinhTienActionPerformed(evt);
            }
        });

        btnXuatHoaDon.setText("Xuất Hóa Đơn");
        btnXuatHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatHoaDonActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("Tiền Khách Đưa");

        lbl_TongTien.setBackground(new java.awt.Color(255, 0, 0));
        lbl_TongTien.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_TongTien.setForeground(new java.awt.Color(255, 0, 0));
        lbl_TongTien.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_TongTien.setText("0 VNĐ");
        lbl_TongTien.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lbl_TongTienAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 153, 153));
        jLabel7.setText("Tiền Thừa:");

        lbl_TienThua.setBackground(new java.awt.Color(255, 0, 0));
        lbl_TienThua.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbl_TienThua.setForeground(new java.awt.Color(255, 0, 0));
        lbl_TienThua.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_TienThua.setText("0 VNĐ");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTinhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnXuatHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_tienKhachDua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(15, 15, 15))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbl_TienThua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(15, 15, 15))))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_TongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_tienKhachDua, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_TienThua, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTinhTien, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXuatHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_QL_NV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_QL_SP, javax.swing.GroupLayout.DEFAULT_SIZE, 205, Short.MAX_VALUE)
                    .addComponent(btn_QL_DT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_dangXuat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_doiMatKhau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_TrangChu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_QL_KH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_QL_NV, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_QL_SP, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_TrangChu, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_QL_KH, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_QL_DT, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(btn_doiMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_dangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_QL_KHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QL_KHActionPerformed
        this.OpenKhachHang();
    }//GEN-LAST:event_btn_QL_KHActionPerformed

    private void btn_TrangChuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TrangChuActionPerformed
        this.OpenTrangChu();
    }//GEN-LAST:event_btn_TrangChuActionPerformed

    private void btn_QL_NVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QL_NVActionPerformed
        this.OpenNhanVien();
    }//GEN-LAST:event_btn_QL_NVActionPerformed

    private void btn_QL_SPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QL_SPActionPerformed
        this.OpenSanPham();
    }//GEN-LAST:event_btn_QL_SPActionPerformed

    private void btnThemKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemKHActionPerformed
        this.insertkh();
    }//GEN-LAST:event_btnThemKHActionPerformed

    private void tblBang_SMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBang_SMouseClicked

        this.fillTableSpCho();
    }//GEN-LAST:event_tblBang_SMouseClicked

    private void btn_doiMatKhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_doiMatKhauActionPerformed
        this.OpenDoiMatKhau();
    }//GEN-LAST:event_btn_doiMatKhauActionPerformed

    private void btn_dangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangXuatActionPerformed
        this.DangXuat();
    }//GEN-LAST:event_btn_dangXuatActionPerformed

    private void btn_QL_DTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QL_DTActionPerformed
        this.OpenDoanhThu();
    }//GEN-LAST:event_btn_QL_DTActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        if (!txtSDT.getText().isEmpty()) {
            if (!txtHoTen.getText().isEmpty()) {
                if (tbl_sanPhamCho.getModel().getRowCount() != 0) {
                    this.them_sua();
                } else {
                    MsgBox.alert(this, "Vui lòng chọn sản phẩm!");
                }
            } else {
                MsgBox.alert(this, "Vui lòng thêm khách hàng mới!");
            }
        } else {
            MsgBox.alert(this, "Vui lòng điền thông tin khách hàng!");
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void tbl_sanPhamChoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tbl_sanPhamChoAncestorAdded

    }//GEN-LAST:event_tbl_sanPhamChoAncestorAdded

    private void tblBang_SAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tblBang_SAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_tblBang_SAncestorAdded

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        timKiem();
    }//GEN-LAST:event_txtTimKiemActionPerformed
    int a = 0;
    private void btnLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMoiActionPerformed
        a = 0;
        DefaultTableModel model = (DefaultTableModel) tbl_sanPhamCho.getModel();
        model.setRowCount(0);
    }//GEN-LAST:event_btnLamMoiActionPerformed

    private void tbl_sanPhamChoAncestorMoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tbl_sanPhamChoAncestorMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_sanPhamChoAncestorMoved

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        this.them_sua();
        this.suaSp();
    }//GEN-LAST:event_btnSuaActionPerformed

    float tong = 0;
    private void lbl_TongTienAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lbl_TongTienAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_lbl_TongTienAncestorAdded

    private void txt_TienThuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TienThuActionPerformed
        int tien = Integer.parseInt(txt_TienThu.getText());
        lbl_tienKhachDua.setText(tien + "");
        this.Bill();
        this.tienThua();
    }//GEN-LAST:event_txt_TienThuActionPerformed

    private void txtSDTAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtSDTAncestorAdded
    }//GEN-LAST:event_txtSDTAncestorAdded

    private void txtSDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSDTActionPerformed

        this.fill();
    }//GEN-LAST:event_txtSDTActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        if (a != 0) {
//            if (tbl_sanPhamCho.getModel().getRowCount() > 0) {
            this.xoaSpCho();
            this.them_sua();
//            } else {
//                MsgBox.alert(this, "Vui lòng chọn hầng cần xóa!");
//            }
        } else {
            MsgBox.alert(this, "Không có sản phẩm!");
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnTinhTienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTinhTienActionPerformed
        if (!txt_TienThu.getText().isEmpty()) {
            if (Float.parseFloat(lbl_tienKhachDua.getText()) < tong) {
                MsgBox.alert(this, "Số tiền nhận vào không được nhỏ hơn tổng tiền!");
            } else {
                this.themHoaDon();
                this.soLuong();
            }
        }
//        fillTableSanPham();
    }//GEN-LAST:event_btnTinhTienActionPerformed

    private void btnXuatHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatHoaDonActionPerformed
        this.Billin();
    }//GEN-LAST:event_btnXuatHoaDonActionPerformed

    private void txtHoTenFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHoTenFocusLost
        if (!txtHoTen.getText().isEmpty()) {
            String reg = "[a-zA-Z\\s]+";
            if (!txtHoTen.getText().trim().matches(reg)) {
                MsgBox.alert(this, "Tên không được chứa sô hay ký tự đặc biệt!");
            }
        }
    }//GEN-LAST:event_txtHoTenFocusLost

    private void txt_TienThuFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_TienThuFocusLost
        if (!txt_TienThu.getText().isEmpty()) {
            String reg = "\\d{4,}";
            if (!txt_TienThu.getText().trim().matches(reg)) {
                MsgBox.alert(this, "Vui lòng nhập đúng đinh dạng!\nVD: 10000.");
                txt_TienThu.setText("");
            }
        }
    }//GEN-LAST:event_txt_TienThuFocusLost

    private void txtSDTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSDTFocusLost
//        if (!txtSDT.getText().isEmpty()) {
//            String reg = "\\d{10,10}";
//            if (!txtSDT.getText().trim().matches(reg)) {
//                MsgBox.alert(this, "Vui lòng nhập đủ 10 số vd:1234567890.");
//                txtSDT.setText("");
//            }
//        }
    }//GEN-LAST:event_txtSDTFocusLost

    String t = "";

    private void btnResetAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetAllActionPerformed
        txtHoTen.setText(t);
        txtSDT.setText(t);
        txtTimKiem.setText(t);
        txt_TienThu.setText(t);
        lbl_TienThua.setText(t);
        lbl_tienKhachDua.setText(t);
        lbl_TongTien.setText(t);
        lblGiamGia.setText(t);
        a = 0;
        DefaultTableModel model = (DefaultTableModel) tbl_sanPhamCho.getModel();
        model.setRowCount(0);
        this.BillreSet();
    }//GEN-LAST:event_btnResetAllActionPerformed

    public void soLuong() {
        try {
            for (int i = 0; i < tbl_sanPhamCho.getRowCount(); i++) {
                String ma = tbl_sanPhamCho.getValueAt(i, 0).toString();
                int sl = Integer.parseInt(tbl_sanPhamCho.getValueAt(i, 2).toString());
                dao.updateSoLuong(sl, ma);
            }
            this.fillTableSanPham();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

//    sanPham getForm() {
//        sanPham sp = new sanPham();
////        sp.setTenSP(sp.getTenSP());
////        sp.setHangSP(sp.getHangSP());
////        sp.setGiaTien(sp.getGiaTien());
////        sp.setSize(sp.getSize());
////        sp.setGhiChu(sp.getGhiChu());
////        sp.setMaNV(sp.getMaNV());
////        sp.setNgayTao(sp.getNgayTao());
////        sp.setHinh(sp.getHinh());
////        sp.setLoaiSP(sp.getLoaiSP());
//        
//        for (int i = 0; i < tbl_sanPhamCho.getRowCount(); i++) {
//            sp.setMaSP(tbl_sanPhamCho.getValueAt(i, 0).toString());
//            sp.setSoLuong(Integer.parseInt(tbl_sanPhamCho.getValueAt(i, 2).toString()));
//            return sp;
////            String maSPCho = tbl_sanPhamCho.getValueAt(i, 0).toString();
////            System.out.println(maSPCho);
////            int soLuongCho = Integer.parseInt(tbl_sanPhamCho.getValueAt(i, 2).toString());
////            System.out.println(soLuongCho);
//        }
//        return sp;
//    }
//    public void soLuong() {
//        sanPham sp = getForm();
//        try {
//            dao.updateSoLuong(sp);
//            this.fillTableSanPham();
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
//    }
    public int maHD() {
        List<hoaDon> list_hd = dao_hd.selectMax();
        int ma = 0;
        for (hoaDon hd : list_hd) {
            ma = hd.getMaHD();
        }
        return ma;
    }

    hoaDonChiTiet getForm_hdct() {
        hoaDonChiTiet hdct = new hoaDonChiTiet();
        hoaDon hd = new hoaDon();
        for (int i = 0; i < tbl_sanPhamCho.getRowCount(); i++) {
            int maHD = maHD();
            hdct.setMaHD(maHD);
            String maSP = (String) tbl_sanPhamCho.getValueAt(i, 0);
            int soLuong = Integer.parseInt(tbl_sanPhamCho.getValueAt(i, 2) + "");
            float gia = (float) tbl_sanPhamCho.getValueAt(i, 4);
            hdct.setMaSP(maSP);
            hdct.setSoLuong(soLuong);
            hdct.setDonGia(gia);
        }
        return hdct;
    }

    public void themHDCT() {
        hoaDonChiTiet hdct = getForm_hdct();
        try {
            dao_hdct.insert(hdct);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    khachHang_DAO dao_kh = new khachHang_DAO();

    hoaDon getForm_hd() {
        hoaDon hd = new hoaDon();
        hd.setNgayTao(new Date());
        hd.setMaNV(Auth.user.getMaNV());
        hd.setTongTien(Float.parseFloat(lbl_TongTien.getText()));
        String keyWord = txtSDT.getText();
        List<KhachHang> list_kh = dao_kh.selectByKeyWord(keyWord);
        for (KhachHang e : list_kh) {
            hd.setMaKH(e.getMaKH());
        }
        return hd;
    }

    public void themHoaDon() {
        hoaDon hd = getForm_hd();
        try {
            dao_hd.insert(hd);
            this.themHDCT();
            txtHoTen.setText("");
            txtSDT.setText("");
            MsgBox.alert(this, "Thanh toán thành công");
        } catch (Exception e) {
            e.printStackTrace();
            MsgBox.alert(this, "Thanh toán thất bại!");
        }
    }

    public void tienThua() {
        float tienThu = Float.parseFloat(txt_TienThu.getText());
        float tienThua = tienThu - this.tong;
        lbl_TienThua.setText(tienThua + "");
    }
    float giamGia = 0;

    public void them_sua() {
        b.setText("");
        tong = 0;
        giamGia = 0;
        for (int i = 0; i < tbl_sanPhamCho.getRowCount(); i++) {
            int soLuong = Integer.parseInt(tbl_sanPhamCho.getValueAt(i, 2) + "");
            float gia = (float) tbl_sanPhamCho.getValueAt(i, 4);
            tong += soLuong * gia;
        }
        if (lblGiamGia.getText().trim().equals("VIP")) {
            giamGia = tong / 100 * 10;
        }
        tong -= giamGia;
        lbl_TongTien.setText(tong + "");
        this.Bill();
    }

    public void Bill() {
        b.setText("                                   NTDK Shop \n");
        b.setText(b.getText() + "                                   Nguyen Van Cu noi dai, \n");
        b.setText(b.getText() + "                                   Nha Toi, Can Tho, \n");
        b.setText(b.getText() + "                                   +098 ********, \n");
        b.setText(b.getText() + "--------------------------------------------------------------------------------\n");
        b.setText(b.getText() + "  Sản Phẩm \t\tSố Lượng \tGiá" + "\n");
        b.setText(b.getText() + "--------------------------------------------------------------------------------\n");

        DefaultTableModel df = (DefaultTableModel) tbl_sanPhamCho.getModel();

        // get table Product details
        for (int i = 0; i < tbl_sanPhamCho.getRowCount(); i++) {

            String Name = df.getValueAt(i, 1).toString();
            String Qty = df.getValueAt(i, 2).toString();
            String Price = df.getValueAt(i, 4).toString();

            String doDaiSp = "";

            // Chia nhỏ tên sản phẩm thành các dòng có 10 ký tự
            for (int j = 0; j < Name.length(); j++) {
                if (j > 0 && j % 15 == 0) {
                    doDaiSp += "\n";
                }
                doDaiSp += Name.charAt(j);
            }

            b.setText(b.getText() + "  " + doDaiSp + "\t\t" + Qty + "\t" + Price + "\n");

            b.setText(b.getText() + "--------------------------------------------------------------------------------\n");
        }
        b.setText(b.getText() + "                                Số điện thoại: " + txtSDT.getText() + "\n");
        b.setText(b.getText() + "                                Họ tên: " + txtHoTen.getText() + "\n");
        b.setText(b.getText() + "                                Tiền khách đưa: " + lbl_tienKhachDua.getText() + "\n");
        b.setText(b.getText() + "                                Tổng tiền: " + lbl_TongTien.getText() + "\n");
        b.setText(b.getText() + "                                Tiền thừa: " + lbl_TienThua.getText() + "\n");

    }

    public void Billin() {
        b.setText("                                   NTDK Shop \n");
        b.setText(b.getText() + "                                   Nguyen Van Cu noi dai, \n");
        b.setText(b.getText() + "                                   Nha Toi, Can Tho, \n");
        b.setText(b.getText() + "                                   +098 ********, \n");
        b.setText(b.getText() + "--------------------------------------------------------------------------------\n");
        b.setText(b.getText() + "  Sản Phẩm \t\tSố Lượng \tGiá" + "\n");
        b.setText(b.getText() + "--------------------------------------------------------------------------------\n");

        DefaultTableModel df = (DefaultTableModel) tbl_sanPhamCho.getModel();

        // get table Product details
        for (int i = 0; i < tbl_sanPhamCho.getRowCount(); i++) {

            String Name = df.getValueAt(i, 1).toString();
            String Qty = df.getValueAt(i, 2).toString();
            String Price = df.getValueAt(i, 4).toString();

            String doDaiSp = "";

            // Chia nhỏ tên sản phẩm thành các dòng có 10 ký tự
            for (int j = 0; j < Name.length(); j++) {
                if (j > 0 && j % 15 == 0) {
                    doDaiSp += "\n";
                }
                doDaiSp += Name.charAt(j);
            }

            b.setText(b.getText() + "  " + doDaiSp + "\t\t" + Qty + "\t" + Price + "\n");

            b.setText(b.getText() + "--------------------------------------------------------------------------------\n");
        }

        try {
            b.setText(b.getText() + "                                Số điện thoại: " + txtSDT.getText() + "\n");
            b.setText(b.getText() + "                                Họ tên: " + txtHoTen.getText() + "\n");
            b.setText(b.getText() + "                                Tiền khách đưa: " + lbl_tienKhachDua.getText() + "\n");
            b.setText(b.getText() + "                                Tổng tiền: " + lbl_TongTien.getText() + "\n");
            b.setText(b.getText() + "                                Tiền thừa: " + lbl_TienThua.getText() + "\n");
            b.print();
        } catch (PrinterException ex) {
            Logger.getLogger(frm_QL_ThanhToan.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void BillreSet() {
        b.setText("                                   NTDK Shop \n");
        b.setText(b.getText() + "                                   Nguyen Van Cu noi dai, \n");
        b.setText(b.getText() + "                                   Nha Toi, Can Tho, \n");
        b.setText(b.getText() + "                                   +098 ********, \n");
        b.setText(b.getText() + "--------------------------------------------------------------------------------\n");
        b.setText(b.getText() + "  Sản Phẩm \t\tSố Lượng \tGiá" + "\n");
        b.setText(b.getText() + "--------------------------------------------------------------------------------\n");

        DefaultTableModel df = (DefaultTableModel) tbl_sanPhamCho.getModel();

        // get table Product details
        for (int i = 0; i < tbl_sanPhamCho.getRowCount(); i++) {

            String Name = df.getValueAt(i, 1).toString();
            String Qty = df.getValueAt(i, 2).toString();
            String Price = df.getValueAt(i, 4).toString();

            String doDaiSp = "";

            // Chia nhỏ tên sản phẩm thành các dòng có 10 ký tự
            for (int j = 0; j < Name.length(); j++) {
                if (j > 0 && j % 15 == 0) {
                    doDaiSp += "\n";
                }
                doDaiSp += Name.charAt(j);
            }

            b.setText(b.getText() + "  " + doDaiSp + "\t\t" + Qty + "\t" + Price + "\n");
            b.setText(b.getText() + "--------------------------------------------------------------------------------\n");
        }
        b.setText(b.getText() + t);

    }

    void timKiem() {
        this.fillTableSanPham();
        this.row = -1;
    }

    public void fillTableSanPham() {
        DefaultTableModel model = (DefaultTableModel) tblBang_S.getModel();
        model.setRowCount(0);
        DefaultTableModel model1 = (DefaultTableModel) tbl_sanPhamCho.getModel();
        model1.setRowCount(0);
        try {
            String timTen = txtTimKiem.getText();
            List<sanPham> list_sp = dao.selectByKeyWord(timTen);
            for (sanPham e : list_sp) {
                Object[] row = {e.getMaSP(), e.getTenSP(), e.getLoaiSP(), e.getSoLuong(), e.getSize(), e.getGiaTien()};
                model.addRow(row);
            }
        } catch (Exception e) {
            e.printStackTrace();
            MsgBox.alert(this, "Lỗi try vấn dữ liệu!");
        }
    }

    public void fillTableSpCho() {
        int y = tblBang_S.getSelectedRow();
        String maSP = (String) tblBang_S.getValueAt(y, 0);
        sanPham sp = dao.selectById(maSP);
        DefaultTableModel model = (DefaultTableModel) tbl_sanPhamCho.getModel();
//        if (a == 0) {
//            model.setRowCount(0);
//            a++;
//        }
        a++;
        Object[] row = {sp.getMaSP(), sp.getTenSP(), sp.getSoLuong(), sp.getSize(), sp.getGiaTien()};
        model.addRow(row);
    }

    public void xoaSpCho() {
        DefaultTableModel modelcho = (DefaultTableModel) tbl_sanPhamCho.getModel();
        int i = tbl_sanPhamCho.getSelectedRow();
        modelcho.removeRow(i);
    }

    KhachHang getForm_kh() {
        if (this.koNull()) {
            return null;
        }
        KhachHang kh = new KhachHang();
        kh.setHoTen(txtHoTen.getText());
        kh.setSdt(txtSDT.getText());
        kh.setNgayDK(new Date());
        return kh;
    }

    String reg = "\\d{10,10}";
    String regten = "[a-zA-Z\\s]+";

    public boolean koNull() {
        if (txtHoTen.getText().isEmpty() || txtSDT.getText().isEmpty()) {
            MsgBox.alert(this, "Không được bỏ trống");
            return true;
        } else if (!txtSDT.getText().trim().matches(reg)) {
            MsgBox.alert(this, "Vui lòng nhập đủ 10 số vd:1234567890.");
            txtSDT.setText("");
            return true;
        } else if (!txtHoTen.getText().trim().matches(regten)) {
            MsgBox.alert(this, "Tên không được chứa sô hay ký tự đặc biệt!");
            return true;
        } else {
            return false;
        }
    }

    void setForm_kh(KhachHang kh) {
        txtHoTen.setText(kh.getHoTen());
        txtSDT.setText(kh.getSdt());
    }

    public void fill() {
        String timKiem = txtSDT.getText();
        List<KhachHang> list_kh = khDao.selectByKeyWord(timKiem);
        for (KhachHang entity : list_kh) {
            Object[] row = {entity.getHoTen(), entity.getSdt()};
            txtHoTen.setText(entity.getHoTen());
            txtSDT.setText(entity.getSdt());
            if (entity.isVip()) {
//                giamGia = tong / 100 * 10;
                lblGiamGia.setText("VIP");
            } else {
                lblGiamGia.setText("");
            }
        }
    }

    void insertkh() {
        KhachHang kh = getForm_kh();
        if (kh == null) {
            return;
        }
        try {
            khDao.insert(kh);
            MsgBox.alert(this, "Thêm mới thành công!");
        } catch (Exception e) {
            e.printStackTrace();
            MsgBox.alert(this, "Thêm mới thất bại!");
        }
    }

    private void suaSp() {
        tbl_sanPhamCho.getModel().addTableModelListener(new TableModelListener() {
            @Override
            public void tableChanged(TableModelEvent e) {
                if (e.getColumn() == 2) { // Giả sử cột số lượng là cột thứ 3 (index 2)
                    capNhatSanPham();
                }
            }
        });
    }

    private void capNhatSanPham() {
        for (int i = 0; i < tbl_sanPhamCho.getRowCount(); i++) {
            String maSPCho = tbl_sanPhamCho.getValueAt(i, 0).toString();
            int soLuongCho = Integer.parseInt(tbl_sanPhamCho.getValueAt(i, 2).toString());
            for (int j = 0; j < tblBang_S.getRowCount(); j++) {
                String maSP = tblBang_S.getValueAt(j, 0).toString();
                if (maSP.equals(maSPCho)) {
                    tblBang_S.setValueAt(soLuongCho, j, 3); // Giả sử cột số lượng là cột thứ 4 (index 3)
                    break;
                }
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_QL_ThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_QL_ThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_QL_ThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_QL_ThanhToan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_QL_ThanhToan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea b;
    private javax.swing.JButton btnLamMoi;
    private javax.swing.JButton btnResetAll;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThemKH;
    private javax.swing.JButton btnTinhTien;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXuatHoaDon;
    private javax.swing.JButton btn_QL_DT;
    private javax.swing.JButton btn_QL_KH;
    private javax.swing.JButton btn_QL_NV;
    private javax.swing.JButton btn_QL_SP;
    private javax.swing.JButton btn_TrangChu;
    private javax.swing.JButton btn_dangXuat;
    private javax.swing.JButton btn_doiMatKhau;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblGiamGia;
    private javax.swing.JLabel lbl_TienThua;
    private javax.swing.JLabel lbl_TongTien;
    private javax.swing.JLabel lbl_tienKhachDua;
    private javax.swing.JTable tblBang_S;
    private javax.swing.JTable tbl_sanPhamCho;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtSDT;
    private javax.swing.JTextField txtTimKiem;
    private javax.swing.JTextField txt_TienThu;
    // End of variables declaration//GEN-END:variables
}
